hexagram_interpretations = {
	"1": "The Creative:\nQuiet your mind.  Kill the noise.  Slow the frantic energy.  This Hexagram is showing you that *if* you make space for your creative energy, success and good fortune will follow.",
	"2": "The Receptive:\nThis Hexagram questions if you are balanced.  Are you on the right path?  The things you do and work on, are they fueled by true motivation or are they clouded by concerns of others, desire for recognition, etc.  This is a time for gentleness, modesty, and receptiveness.",
	"3": "Difficulty at the Beginnging:\nOne of the more straight forward Hexagrams.  This Hexagram was interpreted by ancient sages as a blade of grass trying to break through an obstacle before it sprouts out of the earth.  This Hexagram explicity calls for nonaction.  Bear the discomfort of your situation and the chaos will clear.",
	"4": "Youthful Folly:\nThis Hexagram acknowledges a spiritual immaturity.  It represents fear, anxiety and doubt, even in this reading.  Perhaps you must suspend your mistrust of the unknown.  Let go of preconceived notions of past and future and focus on the immediate.  There is no shame in acknowledging youthful folly, it is the first step toward growth.",
	"5": "Waiting:\nThis Hexagram insists that there is a situation that cannot be corrected by force.  Misfortune will unfold if attention to detail is not paid in full.  Do not sit idly by in discomfort; instead practice patience and careful attention.  Be careful not to compare yourself or siutation to others.",
	"6": "Conflict:\nThis Hexagram highlights an imbalance.  A departure from inner clarity can cause feelings of anxiety, doubt, fear or impatience.  Students of the I Ching recognize that all conflict is inner conflict.  If you follow the negative atributes of conflict, misfortune will unfold.  This Hexagram urges you to disengage momentarily with a problem and to return to quiet contemplation.",
	"7": "The Army:\nLife consists of trials and challenges.  How you conduct yourself in these wars will determine whether the wars are won or lost.  A general who leads their army with brutality and fear runs the risk of losing the support of his/her army when they need it the most.  On the flip side, a general who rules by humane example has the potential to influence inspiration.  What type of general are you going to be?",
	"8": "Holding Together (Union):\nWater over Earth.  This Hexagram shows that union with others can often be helpful to the individual parties.  Think of rain falling to the Earth.  They compliment and help each other.",
	"9": "The Taming of the Small Power:\n   ",
	"10": " :\n   ",
	"11": " :\n   ",
	"12": " :\n   ",
	"13": " :\n   ",
	"14": " :\n   ",
	"15": " :\n   ",
	"16": " :\n   ",
	"17": " :\n   ",
	"18": " :\n   ",
	"19": " :\n   ",
	"20": " :\n   ",
	"22": " :\n   ",
	"23": " :\n   ",
	"24": " :\n   ",
	"25": " :\n   ",
	"26": " :\n   ",
	"27": " :\n   ",
	"28": " :\n   ",
	"29": " :\n   ",
	"30": " :\n   ",
	"31": " :\n   ",
	"32": " :\n   ",
	"33": " :\n   ",
	"34": " :\n   ",
	"35": " :\n   ",
	"36": " :\n   ",
	"37": " :\n   ",
	"38": " :\n   ",
	"39": " :\n   ",
	"40": " :\n   ",
	"41": " :\n   ",
	"42": " :\n   ",
	"43": " :\n   ",
	"44": " :\n   ",
	"45": " :\n   ",
	"46": " :\n   ",
	"47": " :\n   ",
	"48": " :\n   ",
	"49": " :\n   ",
	"50": " :\n   ",
	"51": " :\n   ",
	"52": " :\n   ",
	"53": " :\n   ",
	"54": " :\n   ",
	"55": " :\n   ",
	"56": " :\n   ",
	"57": " :\n   ",
	"58": " :\n   ",
	"59": " :\n   ",
	"60": " :\n   ",
	"61": " :\n   ",
	"62": " :\n   ",
	"63": " :\n   ",
	"64": " :\n   ",
}