odd = "_____________"
even = "_____   _____"


Trigrams = {
	(odd, odd, odd):'Heaven',
	(even, even, odd):'Thunder',
	(even, odd, even):'Water',
	(odd, even, even):'Mountain',
	(even, even, even):'Earth',
	(odd, odd, even):'Wind',
	(odd, even, odd):'Fire',
	(even, odd, odd):'Lake',
}

Hex_Meaning = {
	("Heaven", "Heaven"):'1',
	("Earth", "Earth"):'2',
	("Water", "thunder"):'3',
	("mountain", "Water"):'4',
	("Water", "Heaven"):'5',
	("Heaven", "Water"):'6',
	("Earth", "Water"):'7',
	("Water", "Earth"):'8',
	("Wind", "Heaven"):'9',
	("Heaven", "Lake"):'10',
	("Earth", "Heaven"):'11',
	("Heaven", "Earth"):'12',
	("Heaven", "Fire"):'13',
	("Fire", "Heaven"):'14',
	("Earth", "Mountain"):'15',
	("Thunder", "Earth"):'16',
	("Lake", "Thunder"):'17',
	("Mountain", "Wind"):'18',
	("Earth", "Lake"):'19',
	("Wind", "Earth"):'20',
	("Fire", "Thunder"):'21',
	("Mountain", "Fire"):'22',
	("Mountain", "Earth"):'23',
	("Earth", "Thunder"):'24',
	("Heaven", "Thunder"):'25',
	("Mountain", "Heaven"):'26',
	("Mountain", "Thunder"):'27',
	("Lake", "Wind"):'28',
	("Water", "Water"):'29',
	("Fire", "Fire"):'30',
	("Lake", "Mountain"):'31',
	("Thunder", "Wind"):'32',
	("Heaven","Mountain"):'33',
	("Thunder", "Heaven"):'34',
	("Fire", "Earth"):'35',
	("Earth", "Fire"):'36',
	("Wind", "Fire"):'37',
	("Fire", "Lake"):'38',
	("Water", "Mountain"):'39',
	("Thunder", "Water"):'40',
	("Mountain", "Lake"):'41',
	("Wind", "Thunder"):'42',
	("Lake", "Heaven"):'43',
	("Heaven", "Wind"):'44',
	("Lake", "Earth"):'45',
	("Earth", "Wind"):'46',
	("Lake", "Water"):'47',
	("Water", "Wind"):'48',
	("Lake", "Fire"):'49',
	("Fire", "Wind"):'50',
	("Thunder", "Thunder"):'51',
	("Mountain", "Mountain"):'52',
	("Wind", "Mountain"):'53',
	("Thunder", "Lake"):'54',
	("Thunder", "Fire"):'55',
	("Fire", "Mountain"):'56',
	("Wind", "Wind"):'57',
	("Lake", "Lake"):'58',
	("Wind", "Water"):'59',
	("Water", "Lake"):'60',
	("Wind", "Lake"):'61',
	("Thunder", "Mountain"):'62',
	("Water", "Fire"):'63',
	("Fire", "Water"):'64',
}
